services:
  database:
    container_name: database
    hostname: database
    image: postgres:16.1
    env_file: .env
    volumes:
      - ./database:/var/lib/postgresql/data
    networks:
      - transcendence
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'postgres']
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - 5432:5432

  django:
    container_name: django
    hostname: django
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - ./backend:/app
      - ./certification:/certification
    networks:
      - transcendence
    ports:
      - 8888:8888 # Websockets
    restart: unless-stopped
    depends_on:
      database:
        condition: service_healthy # wait for database to be ready

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file: .env
    networks:
      - transcendence
    ports:
      # - 80:80
      # - 3000:80
      - 443:443
    volumes:
      - ./frontend:/app
      - ./certification:/certification
    restart: unless-stopped
    depends_on:
      - django

networks:
  transcendence:
    name: transcendence-network
    driver: bridge
