services:

  # TODO: Add a database service using PostgreSQL

  backend:
    container_name: backend
    build: 
      context: ./backend 
      dockerfile: ./backend.dockerfile
    volumes:
      - ./backend:/app
    networks:
      - transcendence
    restart: unless-stopped
    ports:
      - "3000:3000" #debugging purpose

  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - "80:80"
      - "5173:5173" # Provide hot reload
    volumes:
      - ./frontend:/app
    networks:
      - transcendence

networks:
  transcendence:
    name: transcendence-network
    driver: bridge
