services:
  postgres:
    container_name: postgres
    hostname: postgres
    image: postgres:latest
    env_file: ./.env
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - transcendence
    restart: unless-stopped

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: ./backend.dockerfile
    volumes:
      - ./backend:/app
    networks:
      - transcendence
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    restart: unless-stopped

networks:
  transcendence:
    name: transcendence-network
    driver: bridge
