# Generated by Django 4.2.7 on 2024-05-15 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roommessages',
            name='message_type',
            field=models.CharField(choices=[('text', 'text'), ('invitation', 'invitation'), ('tournament', 'tournament')], default='text', max_length=10),
        ),
    ]
