# Generated by Django 4.2.7 on 2024-05-15 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_roommessages_message_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='roommessages',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'pending'), ('accepted', 'accepted'), ('rejected', 'rejected')], max_length=10, null=True),
        ),
    ]
