# Generated by Django 4.2.7 on 2024-05-15 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_roommessages_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roommessages',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'pending'), ('accepted', 'accepted'), ('rejected', 'rejected'), ('expired', 'expired')], max_length=10, null=True),
        ),
    ]
