# Generated by Django 4.2.7 on 2024-05-19 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_roommessages_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roommessages',
            name='message_type',
        ),
        migrations.RemoveField(
            model_name='roommessages',
            name='status',
        ),
    ]
