# Generated by Django 4.2.7 on 2024-04-11 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In progress'), ('over', 'Over'), ('canceled', 'Canceled')], default='in_progress', max_length=20),
        ),
    ]
