# Generated by Django 4.2.7 on 2024-02-14 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='statut',
            new_name='status',
        ),
        migrations.RemoveField(
            model_name='game',
            name='players',
        ),
        migrations.RemoveField(
            model_name='game',
            name='winner',
        ),
        migrations.RemoveField(
            model_name='score',
            name='player',
        ),
        migrations.AddField(
            model_name='game',
            name='room_id',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
