# Generated by Django 4.2.7 on 2024-04-05 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0002_game_players_game_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='type',
            field=models.CharField(choices=[('duel', 'Duel'), ('tournament', 'Tournament')], default='duel', max_length=20),
        ),
    ]
