# Generated by Django 4.2.7 on 2024-02-15 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0002_alter_game_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('annulee', 'Annulée'), ('terminee', 'Terminée'), ('en_cours', 'En cours')], default='en_cours', max_length=20),
        ),
    ]
