# Generated by Django 4.2.7 on 2024-04-26 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0002_alter_game_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='round',
            field=models.CharField(choices=[('none', 'None'), ('eighth', 'Eighth Final'), ('quarter', 'Quarter Final'), ('semi', 'Semi Final'), ('final', 'Final')], max_length=20, null=True),
        ),
    ]
