# Generated by Django 4.2.7 on 2024-04-26 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0003_game_round'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='round',
            field=models.CharField(choices=[('none', 'None'), ('quarter', 'Quarter Final'), ('semi', 'Semi Final'), ('final', 'Final')], max_length=20, null=True),
        ),
    ]
