# Generated by Django 4.2.7 on 2024-02-15 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0004_alter_game_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='duration',
        ),
    ]
