# Generated by Django 4.2.7 on 2024-04-25 10:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pong', '0002_alter_game_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('in_progress', 'In progress'), ('over', 'Over'), ('cancelled', 'Cancelled')], default='in_progress', max_length=20)),
                ('active_players', models.ManyToManyField(related_name='active_tournaments', to=settings.AUTH_USER_MODEL)),
                ('games', models.ManyToManyField(related_name='tournament', to='pong.game')),
                ('past_players', models.ManyToManyField(related_name='past_tournaments', to=settings.AUTH_USER_MODEL)),
                ('winner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_tournaments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
