# Generated by Django 4.2.7 on 2024-05-02 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0002_tournament_is_full_tournament_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='size',
            field=models.CharField(choices=[('four', 'Four'), ('eight', 'Eight')], default='four', max_length=10),
        ),
    ]
