# Generated by Django 4.2.7 on 2024-05-03 21:16

from django.db import migrations, models
import users.models
import users.storage


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile_image',
            field=models.ImageField(blank=True, default=users.models.default_profile_image, max_length=255, null=True, storage=users.storage.OverwriteStorage(), upload_to=users.models.profile_image),
        ),
    ]
