# Generated by Django 4.2.7 on 2024-03-13 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_account_confirmation_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='is_two_factor_enabled',
        ),
        migrations.AddField(
            model_name='account',
            name='enabled_2FA',
            field=models.BooleanField(default=False),
        ),
    ]
