# Generated by Django 4.2.7 on 2024-03-13 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_account_is_two_factor_enabled_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='confirmation_code',
        ),
        migrations.AddField(
            model_name='account',
            name='waiting_2FA',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
