# Generated by Django 4.2.7 on 2024-03-14 09:18

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_account_confirmation_code_account_waiting_2fa'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='nb_try_2FA',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='account',
            name='qrcode_2FA',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=users.models.user_qrcode),
        ),
        migrations.AddField(
            model_name='account',
            name='secret_2FA',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='display_name',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='account',
            name='login_intra',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
